config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :cars do
    collection do
      get :my_location
      get :my_booking
    end
   resources :bookings, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # BRAND = ["toyota", "ford", "renault", "peugeot", "audi", "volkswagen", "dacia", "nissan", "citroen", "opel"]

  validates :brand, presence: true
  # validates :brand, inclusion: { in: BRAND }
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, numericality: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_adresse,
    against: [ :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  # BRANDS = ["Toyota", "Ford", "Renault", "Peugeot", "Audi", "Volkswagen", "Dacia", "Nissan", "Citroen", "Opel", "Seat"].sort

  MODELS = ["Auris", "Avensis", "Aygo", "C-HR", "Camry", "Corolla", "Cruiser", "Prius", "Proace", "Rav4", "Yaris",
            "Fiesta", "Focus", "Kuga", "Mustang", "Puma", "Ranger", "Transit",
            "Arkana", "Captur", "Clio", "Espace", "Kadjar", "Kangoo", "Koleos", "Megane", "Twingo", "Zoe",
            "108", "2008", "208", "3008", "301", "308", "5008", "508", "Partner",
            "A1", "A3", "A4", "A5", "E-Tron", "Q3", "Q5", "Q7", "R8",
            "Arteon", "Golf", "Polo", "T-cross", "T-Roc", "Touareg", "Touran",
            "Duster", "Jogger", "Logan", "Sandero",
            "Ariya", "Juke", "Micra", "Qashqai", "X-Trail",
            "Ami", "Berlingo", "C1", "C3", "C4", "Jumper",
            "Astra", "Corsa", "Insignia", "Mokka"]

  BRANDS_MODELS = {"Toyota" => ["Auris", "Avensis", "Aygo", "C-HR", "Camry", "Corolla", "Cruiser", "Prius", "Proace", "Rav4", "Yaris"],
                "Ford" => ["Fiesta", "Focus", "Kuga", "Mustang", "Puma", "Ranger", "Transit"],
                "Renault" => ["Arkana", "Captur", "Clio", "Espace", "Kadjar", "Kangoo", "Koleos", "Megane", "Twingo", "Zoe"],
                "Peugeot" => ["108", "2008", "208", "3008", "301", "308", "5008", "508", "Partner"],
                "Audi" => ["A1", "A3", "A4", "A5", "E-Tron", "Q3", "Q5", "Q7", "R8"],
                "Volkswagen" => ["Arteon", "Golf", "Polo", "T-Cross", "T-Roc", "Touareg", "Touran"],
                "Dacia" => ["Duster", "Jogger", "Logan", "Sandero"],
                "Nissan" => ["Ariya", "Juke", "Micra", "Qashqai", "X-Trail"],
                "Citroen" => ["Ami", "Berlingo", "C1", "C3", "C4", "Jumper"],
                "Opel" => ["Astra", "Corsa", "Insignia", "Mokka"],
                "Seat" => ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco"]
              }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :cars, dependent: :destroy
  has_one_attached :photo

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    date = params[:booking][:starts_at].split
    @booking = Booking.new(starts_at: date.first, ends_at: date.last)
    authorize @booking
    @car = Car.find(params[:car_id])
    authorize @car
    @booking.car = @car
    @booking.user = current_user
      if @booking.save
        flash[:notice] = "Vous avez-bien réservé votre #{@car.brand} #{@car.model} ! Merci pour votre confiance"
        redirect_to my_booking_cars_path
      else
        redirect_to car_path(@car), notice: "La réservation n'a pas pu être faite...."
      end
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    # raise
    if params[:address].present?
      @cars = policy_scope(Car).near(params[:address], 15).where.not(latitude: nil, longitude: nil)
      # @cars = Car.near(params[:address], 15).where.not(latitude: nil, longitude: nil)

      @markers = @cars.geocoded.map do |car|
        {
          lat: car.latitude,
          lng: car.longitude,
          info_window: render_to_string(partial: "info_window", locals: { car: car })
        }
      end
    else
      @cars = policy_scope(Car)
    end
  end

  def my_location
    @cars = Car.where(user: current_user)
    authorize @cars
  end

  def my_booking
    @bookings = Booking.where(user: current_user)
    # @cars = Car.where(user: current_user)
    # authorize @cars
    authorize @bookings
  end

  def show
    @booking = Booking.new

    @cars = Car.where(address: @car.address)
    @markers = @cars.geocoded.map do |car|
        {
          lat: car.latitude,
          lng: car.longitude,
          info_window: render_to_string(partial: "info_window", locals: { car: car })
        }
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car), notice: 'Votre voiture a bien été mise à jour'
    else
      render :edit
    end
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car
    if @car.save!
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @car.destroy
    if current_user.admin
      redirect_to my_location_cars_path, notice: 'Votre voiture a bien été suprimée'
    else
      redirect_to my_location_cars_path, notice: 'Votre voiture a bien été suprimée'
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:brand, :model, :year_of_production, :address, :price_per_day, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_accordeon-cache.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        Some placeholder content for the first accordion panel. This panel is shown by default, thanks to the <code>.show</code> class.
      </div>
    </div>
  </div>
</div>

app/views/cars/back_up.html.erb
<div class="banner-car">
  <div class="container-banner-car">
    <%= form_tag cars_path, method: :get, class:"search" do %>
      <div class="search-address">
        <label for="address" class="search-label">Retrait et retour</label>
        <div class="search-inline">
          <i class="fas fa-search white-color"></i>
          <%= text_field_tag :address, params[:address], class: "form-control", placeholder: "Mérignac" %>
        </div>
      </div>
      <div class="search-depart">
        <label for="depart" class="search-label">Date de départ</label>
        <div class="search-inline">
          <%= text_field_tag :depart, params[:depart], class: "form-control", placeholder: "17 déc" %>
          <%= text_field_tag :dep_hour, params[:dep_hour], class: "form-control", placeholder: "10:30" %>
        </div>
      </div>
      <div class="search-arrivee">
        <label for="arrivee" class="search-label">Date de retour</label>
        <div class="search-inline">
          <%= text_field_tag :arrivee, params[:arrivee], class: "form-control", placeholder: "19 déc" %>
          <%= text_field_tag :arr_hour, params[:arr_hour], class: "form-control", placeholder: "08:00" %>
        </div>
      </div>
      <%= submit_tag "Rechercher", class: "btn btn-primary rechercher" %>
    <% end %>
  </div>
</div>


<li class="nav-item dropdown" id="clic-avatar">
  <div class="avatar-display">
    <%= current_user.first_name %>
    <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "Accueil", root_path, class: "dropdown-item" %>
      <%= link_to "Liste des véhicules", cars_path, class: "dropdown-item" %>
      <%= link_to "Louer ma voiture", new_car_path, class: "dropdown-item" %>
      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
  </div>
</li>

app/views/cars/index.html.erb
<div class="banner-car">
  <div class="container-banner-car">
    <%= form_tag cars_path, method: :get, class:"search" do %>
      <div class="search-address">
        <%# <label for="address" class="search-label">Lieu de départ</label> %>
        <div class="search-inline" id="mobile-search-index">
          <%# <i class="fas fa-search white-color"></i> %>
          <%= text_field_tag :address, params[:address], class: "form-control-home", placeholder: "Entrez une ville..." %>
        </div>
      </div>
      <%= submit_tag "Rechercher", class: "btn rechercher", id:"btn-rechercher-index"%>
    <% end %>
  </div>
</div>

<div class="container-cars-index">
  <div class="voirlacarte-inline">
    <div class="btn rechercher" id="btn-carte">
      <p class="voir-carte"><i class="fas fa-map-marked-alt mr-2"></i>Carte</p>
      <p class="voir-liste hidden"><i class="fas fa-list-ul mr-2"></i>Liste</p>
    </div>
    <p class="trait"> <%= pluralize @cars.size, "Résultats" %></p>
  </div>
  <div class="d-none map-js">
    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <div class="cards">
    <% @cars.each do |car| %>
      <%= button_to(car_path(car), method: :get, class: "btn-stripped" ) do %>
        <div class="card">
          <div class="card-photo">
              <% if car.photo.attached? %>
                <%= cl_image_tag("#{car.photo.key}", crop: :fill, class: "card-photo") %>
              <% else %>
                <%= image_tag 'card-en-construction-01.png', crop: :fill, class: "card-photo" %>
              <% end %>
              <%#= image_tag 'card-en-construction-01.png', crop: :fill, class: "card-photo" %>
          </div>
          <div class="card-body">
            <div class="text">
              <div class="card-body-title">
                <h3 class="card-title m-0"><%= car.brand %></h3>
                <h3 class="car-model ml-2 mb-0"><%= car.model %></h3>
              </div>
              <div class="card-body-description">
                <p></p>
              </div>
            </div>
            <div class="price">
              <p class="value-price"><%= car.price_per_day.to_i %> €</p>
              <p>Par jour</p>
            </div>
          </div>
          <div class="card-links">
            <% if policy(car).edit? %>
              <%#= link_to 'Edit', edit_car_path(car) %>
              <%= link_to edit_car_path(car) do %>
                <i class="fas fa-user-edit"></i>
              <% end %>
            <% end %>
            <% if policy(car).destroy? %>
              <%= link_to(car_path(car), method: :delete, remote: true, data: { confirm: "Souhaitez-vous supprimer cette voiture ?" } ) do %>
                <i class="fas fa-trash-alt ml-1"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if @cars.empty? %>
    <p class="text-left message-no-card">Vous n'avez pas de véhicules qui correspondent à votre recherche...</p>
  <% end %>
</div>

app/views/cars/my_location.html.erb
<div class="container-cars-location">
  <h3>Mes locations</h3>
    <% if @cars.empty? %>
      <p class="text-left message-no-card">Oupss... Vous n'avez pas encore de locations...</p>
      <p class="text-left ajout-location"><strong>Souhaitez-vous en créer une ?</strong></p>
      <%= link_to "Ajouter une location", new_car_path, class:"btn rechercher", id:"btn-carte-new-location" %>
    <% else %>
      <div class="cards">
        <% @cars.each do |car| %>
          <%= button_to(car_path(car), method: :get, class: "btn-stripped" ) do %>
            <div class="card">
              <div class="card-photo">
                  <% if car.photo.attached? %>
                    <%= cl_image_tag("#{car.photo.key}", crop: :fill, class: "card-photo") %>
                  <% else %>
                    <%= image_tag 'card-en-construction-01.png', crop: :fill, class: "card-photo" %>
                  <% end %>
                  <%#= image_tag 'card-en-construction-01.png', crop: :fill, class: "card-photo" %>
              </div>
              <div class="card-body">
                <div class="text">
                  <div class="card-body-title">
                    <h3 class="card-title m-0"><%= car.brand %></h3>
                    <h3 class="car-model ml-2 mb-0"><%= car.model %></h3>
                  </div>
                  <div class="card-body-description">
                    <p></p>
                  </div>
                </div>
                <div class="price">
                  <p class="value-price"><%= car.price_per_day.to_i %> €</p>
                  <p>Par jour</p>
                </div>
              </div>
              <div class="card-links">
                <% if policy(car).edit? %>
                  <%#= link_to 'Edit', edit_car_path(car) %>
                  <%= link_to edit_car_path(car) do %>
                    <i class="fas fa-user-edit"></i>
                  <% end %>
                <% end %>
                <% if policy(car).destroy? %>
                  <%= link_to(car_path(car), method: :delete,  data: { confirm: "Souhaitez-vous supprimer cette voiture ?" } ) do %>
                    <i class="fas fa-trash-alt ml-1"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= link_to "Ajouter une nouvelle location", new_car_path, class:"btn rechercher mb-4", id:"btn-carte-new-location" %>
    <% end %>
</div>

app/views/shared/_back-up navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="top-menus">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-ezycar.svg", class:"logo" %>
    <% end %>

    <div class="menus">
      <%= link_to 'Accueil', root_path, class:"menu-link", id:"acceuil" %>
      <%= link_to 'Listes des véhicules', cars_path, class:"menu-link" %>
      <% if policy(Car).create? %>
        <%= link_to 'Louer ma voiture', new_car_path, class:"menu-link btn", id:"louer"%>
      <% end %>
    </div>
  </div>

  <li class="nav-item dropdown" id="clic-avatar-mobile">
    <div class="avatar-display">
      <p><%= current_user %><%#= current_user.first_name %></p>
      <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "Accueil", root_path, class: "dropdown-item" %>
        <%= link_to "Liste des véhicules", cars_path, class: "dropdown-item" %>
        <%= link_to "Louer ma voiture", new_car_path, class: "dropdown-item" %>
        <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  </li>

  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <div class="mobile-menu">Menus<span class="navbar-toggler-icon ml-2"></span></div>
  </button> %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="links-mobiles">
          <%= link_to "Accueil", root_path, class: "nav-item mobile-only" %>
          <%= link_to "Liste des véhicules", cars_path, class: "nav-item mobile-only" %>
          <%= link_to "Louer ma voiture", new_car_path, class: "nav-item mobile-only" %>
          <li class="nav-item dropdown" id="clic-avatar">
            <div class="avatar-display">
              <p><%= current_user.first_name %></p>
              <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Accueil", root_path, class: "dropdown-item" %>
                <%= link_to "Liste des véhicules", cars_path, class: "dropdown-item" %>
                <%= link_to "Louer ma voiture", new_car_path, class: "dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          </li>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link inscription" do %>
            <i class="fas fa-user-circle mr-1"></i><p>CONNEXTION&thinsp;|&thinsp;INSCRIPTION</p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="top-menus">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-ezycar-blanc.png", class:"logo mr-2" %>
    <% end %>

    <div class="menus">
      <%= link_to 'Accueil', root_path, class:"menu-link", id:"acceuil" %>
      <%= link_to 'Listes des véhicules', cars_path, class:"menu-link" %>
      <% if user_signed_in? %>
        <%= link_to "Voir mes locations",  my_location_cars_path, class: "menu-link" %>
        <% if policy(Booking).create? %>
          <%= link_to 'Voir mes réservations', my_booking_cars_path, class:"menu-link" %>
        <% end %>
      <% end %>
      <% if policy(Car).create? %>
        <%= link_to 'Louer ma voiture', new_car_path, class:"menu-link btn mr-3", id:"louer"%>
      <% end %>
    </div>
  </div>
  <li class="nav-item dropdown" id="clic-avatar">
    <div class="avatar-display">
      <% if user_signed_in? %>
        <%= current_user.first_name %>
        <%#= image_tag "avatar.svg", class: "ml-2 avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag("#{current_user.photo.key}", class: "ml-2 avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% else %>
          <%= image_tag "avatar.svg", class: "ml-2 avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Accueil", root_path, class: "dropdown-item" %>
          <%= link_to "Modifier mon compte", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Liste des véhicules", cars_path, class: "dropdown-item" %>
          <%= link_to "Louer ma voiture", new_car_path, class: "dropdown-item" %>
          <%= link_to "Voir mes locations",  my_location_cars_path, class: "dropdown-item" %>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% else %>
        <%= link_to new_user_session_path, class:"menu-link", id:"connexion" do %>
          <p class="se-connecter">Se connecter</p>
          <%= image_tag "avatar.svg", class: "ml-2 avatar dropdown-toggle" %>
        <% end %>
        <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"> %>
          <%#= link_to "Accueil", root_path, class: "dropdown-item" %>
          <%#= link_to "Liste des véhicules", cars_path, class: "dropdown-item" %>
          <%#= link_to "Louer ma voiture", new_car_path, class: "dropdown-item" %>
          <%#= link_to "Voir mes locations",  my_location_cars_path, class: "dropdown-item" %>
        <%# </div> %>
      <% end %>
    </div>
  </li>

  <% if user_signed_in? %>
    <button class="navbar-toggler modal-btn" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <div class="mobile-menu">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag("#{current_user.photo.key}", class: "avatar") %>
        <% else %>
          <%= image_tag "avatar.svg", class: "avatar" %>
        <% end %>
        <span class="navbar-toggler-icon ml-2"></span></div>
    </button>
  <% else %>
    <button class="navbar-toggler modal-btn" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <div class="mobile-menu">Menus<span class="navbar-toggler-icon ml-2"></span></div>
    </button>
  <% end %>

  <div class="modal-bg">
    <div class="modal-container">
        <span class="modal-close" id="modal-close-new"></span>
        <%#= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% if user_signed_in? %>
          <div class="profil-user">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag("#{current_user.photo.key}", class: "avatar-large") %>
            <% else %>
              <%= image_tag "avatar.svg", class: "avatar-large" %>
            <% end %>
            <div class="profil-text">
              <p><%= current_user.first_name %>&nbsp;<%= current_user.last_name %></p>
              <%= link_to "Modifier mon compte", edit_user_registration_path, class: "dropdown-item" %>
            </div>
          </div>
          <div class="nav-links-mobiles">
            <div class="links-in-line">
              <%= link_to "Accueil", root_path, class: "dropdown-item" %>
              <%= image_tag "home.svg", class: "picto-menus", id:"smaller2" %>
            </div>
            <div class="links-in-line">
              <%= link_to "Rechercher une voiture", cars_path, class: "dropdown-item" %>
              <svg xmlns="http://www.w3.org/2000/svg" class="picto-menus" id="smaller" viewBox="0 0 19 19"><path fill="#191919" d="M17 7A5 5 0 107 7a5 5 0 0010 0zm-9.192 5.607l-6.1 6.1-1.415-1.414 6.1-6.1A7 7 0 0112 0a7 7 0 11-4.192 12.606z"></path></svg>
            </div>
            <div class="links-in-line">
              <%= link_to "Louer ma voiture", new_car_path, class: "dropdown-item" %>
              <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="picto-menus"><path d="M20.382 8.539C19.539 5.819 17.86 4 15.5 4h-7C6.14 4 4.46 5.82 3.618 8.539a1.75 1.75 0 10-.59 3.447C3.01 12.32 3 12.657 3 13v6a1 1 0 001 1h2a1 1 0 001-1v-1h10v1a1 1 0 001 1h2a1 1 0 001-1v-6c0-.343-.01-.681-.028-1.014a1.75 1.75 0 10-.59-3.447zM5.5 11c0-1 0-5 3.5-5h6c3.5 0 3.5 4 3.5 5h-13zm12 5a1.5 1.5 0 110-3 1.5 1.5 0 010 3zm-11 0a1.5 1.5 0 110-3 1.5 1.5 0 010 3z"></path></svg>
            </div>
            <div class="links-in-line">
              <%= link_to "Voir mes locations",  my_location_cars_path, class: "dropdown-item" %>
              <%= image_tag "locations.svg", class: "picto-menus", id:"picto-menus" %>
            </div>
            <div class="links-in-line" id="last-link">
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="picto-menus"><path clip-rule="evenodd" d="M14.08 15.59L16.67 13H7v-2h9.67l-2.59-2.59L15.5 7l5 5-5 5zM19 3a2 2 0 012 2v4.67l-2-2V5H5v14h14v-2.67l2-2V19a2 2 0 01-2 2H5a2 2 0 01-2-2V5c0-1.11.89-2 2-2z" fill-rule="evenodd"></path></svg>
            </div>
          </div>
        <% else %>
          <div class="nav-item-mobile">
            <%= link_to new_user_session_path, class:"btn connexion" do %>
              <%# <i class="fas fa-user-circle mr-1"></i>%><p>Se connecter</p>
            <% end %>
            <div class="nav-links-mobiles">
              <%= link_to "Accueil", root_path, class: "dropdown-item" %>
              <%= link_to "Liste des véhicules", cars_path, class: "dropdown-item" %>
              <%= link_to "Louer ma voiture", new_car_path, class: "dropdown-item", id:"last-link" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>

</div>